### PR TITLE
Rename deprecated API for iOS 8

### PR DESCRIPTION
**Pull request by kostiakoval**

### CODE REVIEW

**Comment by NSElvis** [comment]
Damn, doesn't seem like the guy is supporting his pod. I'll do some magic :D

**Comment by kostiakoval** [comment]
We can keep supporting it and make it better in our fork :)

**Comment by NSElvis** [comment]
That was my exact thought!

**Comment by NSElvis** [comment]
Do you know if it solves the performance issues of NSDateFormatter?

http://blog.soff.es/how-to-drastically-improve-your-app-with-an-afternoon-and-instruments/

**Comment by kostiakoval** [comment]
I think yes, but I have't measured it.

**Comment by zygoat** [comment]
Hey guys. Can you point me to your fork? Is it in CocoaPods? I've recently begun using this one, but realized shortly that building under iOS 8.0 results in lots of deprecation spew, and sadly clued in that this appears to be abandoned. Is there a maintained replacement?

**Comment by 3lvis** [comment]
@zygoat You can use `pod HYP8601`

https://github.com/hyperoslo/HYP8601

**Comment by boredzo** [comment]
I fixed the performance problems a long time ago. And this isn't abandoned; I merged in a fix just recently. (I will admit I don't always look at my email often enough. ☺)

I want to get more test coverage before I accept larger changes, though.

**Comment by 3lvis** [comment]
@boredzo This isn't about performance, I think `iso-8601-date-formatter` doesn't have problems in that area. It's about the deprecations and Xcode warnings. :)

**Comment by boredzo** [comment]
I've been going through the PRs one at a time today. I merged #42 earlier, which covers the same territory as this one. Thanks, though!

**Pull request closed without merging**
