### PR TITLE
Add tvOS targets

### PR DESCRIPTION
**Pull request by neonichu**
This adds a framework target and test target for tvOS.

### CODE REVIEW

**Comment by neonichu** [comment]
If this gets merged, it would be great if there could also be a new point release and an update of the podspec on trunk to add tvOS support :ok_hand:

**Comment by kikin81** [comment]
@neonichu 
Hey Boris,
I am currently working on an apple tv app and would like to use your fork of this iso library.
When I try to point this library to your commit, I get an error that ISO8601DateFormatter does not have a podspec.

Do you have any special instructions on how to set up the import for this?

Thank you.

**Comment by boredzo** [comment]
Is there an advantage to having a separate target, vs adding AppleTV as a supported platform to the existing target?

**Comment by victor** [comment]
I needed this library for an AppleTV project, all I needed to do was add tvOS as a deployment target to my local copy of the podspec.
I'd appreciate it if the project adopted an official podspec in the repo itself, and with tvOS support if possible, so as to have a simpler Podfile.

**Comment by neonichu** [comment]
@boredzo probably not, I didn't know that was possible

**Comment by neonichu** [comment]
I updated the PR so that it adds tvOS support to the existing CocoaTouch targets — much cleaner, thanks for the suggestion :+1:

**Comment by boredzo** [comment]
Thanks for getting this done!

**Comment by neonichu** [comment]
Thanks for merging! Would be great if you could also push a new release to CocoaPods trunk at some point with the additional platform support.

**Comment by iGranDav** [comment]
Hi, just want to up this subject to push the tvOS compatible version to CocoaPods trunk please.

**Pull request merged**
